<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Reports.aspx.cs" Inherits="Reports_Reports" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
    <link href="../Css/style.css" rel="stylesheet" type="text/css" />
    <style >
        .print:last-child {
     page-break-after: auto;
}   
     </style>
     <script src="../js/jquery.js" type="text/javascript"></script>

   <script language="javascript" type="text/javascript">

       function printThis() {         	
           var btn = document.getElementById('Print')
           if (btn.style.visibility == "visible" || btn.style.visibility=="")
               btn.style.visibility = "hidden";
           else
               btn.style.visibility = "hidden";
           window.print();
           btn.style.visibility = "visible";
          
       }
       function printdoc() {
           $("#Print").hide();
           //var printarea = $("#main").html();
           //var w = window.open();
          // w.document.writeln(printarea);
           window.print();
           $("#Print").show();
           //document.getElementById("Print").style.visibility = true;
       }
      
   </script>  


    <style type="text/css">
        .style1
        {
            height: 78px;
        }
    </style>


</head>
<body>
    <form id="form1" runat="server">
    <div >
        <table width="100%" class="Table">
            <tr>
                <td>
                    <%--<img src="../Images/Images/logo.gif" />--%>
                 <%--   <img src="../Images/Images/OmnipolisLogo.png" border="0" style="width: 207px; height: 71px" />--%>
               
                             <%--  <h3>CMS</h3>  --%>
                </td>
                <td valign="top" align="right" colspan="2" style="height: 30%">
              <%--      <asp:Label ID="lblGeneratedBy" runat="server" Text="Generated By:" Style="font-family: Verdana;color: gray"></asp:Label>
                    <asp:Label ID="lblGeneratedDate" runat="server" Text="||Generated Date:" Style="font-family: Verdana;color: gray"></asp:Label>--%>
                </td>
                <td>
                </td>
            </tr>
        </table>
    </div>
    <div id="main" >
        <table cellpadding="0" cellspacing="0" width="90%" class='Table'>
            <tr bgcolor="white" valign="top">
                <td class="style1">
                    <table align="center" style="vertical-align: middle">
                        <tr align="center">
                            <td align="center">
                                <span>
                                    <asp:Label ID="lblReportName" Text="" runat="server" Style="font-family: Verdana;
                                        font-weight: bold; color: gray"></asp:Label></span>
                            </td>
                        </tr>
                        </table>
                    <br />
                    <br />
                    <asp:Panel ID="pnlLogin" runat="server">

                        <%--<script language="javascript" src="../Scripts/Validations.js" type="text/javascript"></script>--%>

                        <div id="tblData" runat="server" >
                          
                        </div>
                        <center><asp:Label ID="lblText" runat="server" Visible="false"></asp:Label></center>
                    </asp:Panel>
                </td>
            </tr>
            <tr >
                <td> 
                 &nbsp                          
                  
                 </td>
            </tr>
            <tr>
                <td>
                    &nbsp
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp
                </td>
            </tr>
        </table>
         
    </div>
  
    <div>
         <table width="90%" align="center">
        <tr><td align="center">
            <input type='button'   id='Print' name='Print' value="Print" onclick='printThis()'/>
         </td></tr>
        </table>
    </div>
    </form>
</body>
</html>
